source 'https://rubygems.org'

group :development, :test do
  # Original bootstrap45 gems:
  gem 'jekyll', '~> 4.1.1'
  gem 'jekyll-redirect-from', '~> 0.16.0'
  gem 'jekyll-sitemap', '~> 1.4.0'
  gem 'jekyll-toc', '~> 0.14.0'
  gem 'wdm', '~> 0.1.1', :install_if => Gem.win_platform?

  # ProjectSite additions:
  gem 'jekyll-spaceship', '~> 0.9.8'
end
