alias ll='ls -l'
alias la='ls -la'

alias ..='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'

alias gbr='git branch'
alias gcn='git clean -dxn'
alias gcf='git clean -dxf'
alias gd='git diff'
alias grhh='git reset --hard'
alias grv='git remote -v'
alias gst='git status'
alias gsti='git status --ignored'

alias jb='bundle exec jekyll build'
alias js='bundle exec jekyll serve --skip-initial-build --host 0.0.0.0'
